# Write git hub action file to bhuild each docker images of each service whenever pushed to the main branch,
# and push the image to docker hub
# The docker hub credentials are stored in the secrets of the repository
name: Build and Push Docker Images
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          for dir in */; do
            if [ -d "$dir" ]; then
              echo "Building and pushing image for $dir"
              docker buildx build --push --tag your-dockerhub-username/${{ github.event.repository.name }}:${{ github.sha }} $dir
            fi
          done
      - name: Logout from Docker Hub
        run: |
          echo "Logging out from Docker Hub"
          docker logout
